@startuml
actor User as U

rectangle Website {
    usecase "View Home Page" as UC1
    usecase "View Plot Page" as UC2
    usecase "View Characters Page" as UC3
    usecase "View Gallery Page" as UC4
    usecase "View Author Page" as UC5
    usecase "Hover over Images to zoom" as UC6
    usecase "Hover over images to see description" as UC7
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
UC4 --> UC6
UC3 --> UC7

@enduml
